### ISSUE TITLE
어떤 주제를 선택할까요??

### ISSUE THREAD

**Issue by drone8449** [readable-ko/Miniproject_2#3]
자유롭게 의견 주세요!

**Comment by readable-ko** [comment]
실종 반려동물 찾기, 출석부, rc별 오프라인 채플 참석자 명단, 매점 음식 메뉴 등 어떨까요

**Comment by drone8449** [comment]
저는 실종 반려동물 찾기 괜찮은거 같아요
정보 딱 정해져있고 다른 조하고 겹칠 일도 없을거 같고요!!

**Comment by readable-ko** [comment]
그러면 실종 반려동물 찾기로 하죠!
