### ISSUE TITLE
역할 분담은 어떻게 할까요?? 

### ISSUE THREAD

**Issue by drone8449** [readable-ko/Miniproject_2#4]
의견 주세요!

**Comment by readable-ko** [comment]
CRUD / 찾기 함수 1개
load data / save data / 찾기 함수 3개
로 나눠 개발하고 merge 하는 방법은 어떨까요

**Comment by readable-ko** [comment]
먼저 반려동물의 어떤 특징들을 나열할지도 알아야할 것 같아요!

**Comment by drone8449** [comment]
찾기 함수는 3개로만 하고 
CRUD / 메뉴 선택
load / save / 찾기 3개는 어떠세요??

**Comment by drone8449** [comment]
특징들은 이슈 새로 팔게요!!

**Comment by readable-ko** [comment]
아 좋습니다 그럼 어떤 쪽 개발이 편하세요

**Comment by drone8449** [comment]
사다리 타서 결정지을까요??

**Comment by readable-ko** [comment]
네 그럽시다

**Comment by drone8449** [comment]
사다리 탄 결과
CRUD / 메뉴 선택는 영광 학우님이
load / save / 찾기 3개는 제가 하면 될거 같습니다!!

**Comment by readable-ko** [comment]
![image](https://user-images.githubusercontent.com/70497430/116803509-3719b900-ab53-11eb-88af-6d3cb30a9262.png)
