### ISSUE TITLE
반려동물을 찾기 위한 정보들로는

### ISSUE THREAD

**Issue by drone8449** [readable-ko/Miniproject_2#5]
어떤 정보들이 필요할까요??

ex) 나이 견종 성별..

**Comment by readable-ko** [comment]
이름 나이 견종 성별 사례금으로 하는게 어떨까요?

**Comment by drone8449** [comment]
좋은거 같아요!!
이름은 string 나이는 int 견종은 string 성별은 string 사례금은 int로 데이터형 생각할까요??

**Comment by readable-ko** [comment]
좋아요!! 그럼 일단 간단하게 그 정도로만 하고 추가적으로 필요한 기능 생기면 그 때 그 때 이슈 파서 사로 생성하도록 할까요?

**Comment by drone8449** [comment]
넵넵 마무리할게요
