### ISSUE TITLE
함수들은 어떻게 정의할까요??

### ISSUE THREAD

**Issue by drone8449** [readable-ko/Miniproject_2#8]
일단 제가 맡은 load/save/search에서는 

int loadData(Animal s[]);                              // 유기 동물 리스트 파일을 로드
void saveData(Animal s[], int count);                           // 유기 동물 리스트를 파일로 저장
void searchName(Animal *s, int count);     // 유기 동물 이름 검색
void searchType(Animal *s, int count);       // 유기 동물 견종&묘종 검색
void searchAge(Animal *s, int count);        //  유기 동물 나이 검색

이렇게 하면 될 것 같아요!!

**Comment by readable-ko** [comment]
typedef struct {
 char name[50];
 int age;
 char breed[50];
 char sex;
 int gratuity;
} Animal;

int selectMenu();
int createAnimal(Animal *a);
void readAnimal(Animal a);
int updateAnimal(Animal *a);
int deleteAnimal(Animal *a);

void listAnimal(Animal *alist, int count);
int selectNumber(Animal *alist, int count);

제 함수들은 이렇게 구현했습니다!
따로 태현학우님 함수만 다른 header에 구현하고 merge하는건 어떨까요

**Comment by drone8449** [comment]
넵넵 그렇게 하죠
구조체는 위키 개발일지에 추가해놓긴 했었는데 함수도 정리해서 개발일지에 적을게요

**Comment by readable-ko** [comment]
넵넵 :)

**Comment by readable-ko** [comment]
코드 올려놓았으니 pull 부탁드려요~!

**Comment by drone8449** [comment]
네엡
