### ISSUE TITLE
WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가) 

### ISSUE THREAD

**Issue by readable-ko** [readable-ko/Miniproject_2#9]
WIKI에서 완성된 함수 설명 및 결과 이미지를 이용한 페이지 추가(md 페이지 추가) 
여기서 함수 설명과 결과 이미지는 서비스 상세에 넣는게 어떨까요?
그리고 md 페이지를 추가하라는게 무슨 의미인지 혹시 아시나요

**Comment by drone8449** [comment]
음 위키 자체가 md 페이지로 구성된거라서 wiki 추가하고 추가된 링크를 URL로 제출하면 될거 같아요
서비스 상세도 좋긴한데 개발일지에 넣는 것도 괜찮아보이는데요??

**Comment by readable-ko** [comment]
그럼 개발일지 페이지에 함수 설명과 결과 이미지 추가하고 완성된 wiki url 올리는 방향으로 할께요!
아마 내일쯤 완료할 것 같습니다. 완료되면 이슈+카톡으로 알려드릴께요 :)

**Comment by drone8449** [comment]
넵넵 알겠습니다 테스트는 제가 하는게 더 좋을거 같은데 그렇게 할까요??
다음번 제가 코딩한건 영광학우님이 테스트해주시는 거죠!!

**Comment by readable-ko** [comment]
아 그게 서로 기능알아보고 하긴 좋을 것 같네요! 그렇게 하죠!!

**Comment by drone8449** [comment]
넵 완료되면 알려주세요 :)

**Comment by readable-ko** [comment]
![image](https://user-images.githubusercontent.com/70497430/117578228-55ba1a00-b128-11eb-867d-49ef27f074a0.png)
![image](https://user-images.githubusercontent.com/70497430/117578235-5baffb00-b128-11eb-951d-7f42ab47e663.png)
![image](https://user-images.githubusercontent.com/70497430/117578237-5eaaeb80-b128-11eb-84c0-ad7949e23cc7.png)
